"""initial schema

Revision ID: eb5af684744f
Revises: 
Create Date: 2026-09-04 01:20:46.395980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb5af684744f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('product_url', sa.String(length=1024), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_product_price_nonneg'),
    sa.CheckConstraint('stock >= 0', name='ck_product_stock_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_product_source_external')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_product_active', ['active'], unique=False)
        batch_op.create_index('ix_product_category', ['category'], unique=False)
        batch_op.create_index('ix_product_sku', ['sku'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_source'), ['source'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('state', sa.Enum('BROWSING', 'CART_BUILDING', 'CART_REVIEW', 'UPSELL', 'PAYMENT_PENDING', 'PAYMENT_FAILED', 'COMPLETED', name='sessionstate', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upsell_shown', sa.Boolean(), nullable=False),
    sa.Column('upsell_accepted', sa.Boolean(), nullable=False),
    sa.Column('upsell_declined', sa.Boolean(), nullable=False),
    sa.Column('chat_history', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('session_id', sa.String(length=48), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CHECKOUT', 'COMPLETED', 'ABANDONED', name='cartstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carts_session_id'), ['session_id'], unique=True)

    op.create_table('cart_items',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('cart_id', sa.String(length=48), nullable=False),
    sa.Column('product_id', sa.String(length=48), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_cart_item_qty_pos'),
    sa.CheckConstraint('unit_price >= 0', name='ck_cart_item_price_nonneg'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_item_cart_product')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_product_id'), ['product_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('session_id', sa.String(length=48), nullable=False),
    sa.Column('cart_id', sa.String(length=48), nullable=False),
    sa.Column('open_cart_key', sa.String(length=48), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAYMENT_PENDING', 'PAID', 'PAYMENT_FAILED', 'CANCELLED', name='orderstatus', native_enum=False, length=24), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('shipping', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('receipt', sa.String(length=40), nullable=True),
    sa.Column('stock_reserved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_order_amount_nonneg'),
    sa.CheckConstraint('subtotal >= 0 AND shipping >= 0 AND tax >= 0', name='ck_order_parts_nonneg'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_cart_key')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_razorpay_order_id'), ['razorpay_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_session_id'), ['session_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('session_ref', sa.String(length=48), nullable=True),
    sa.Column('session_id', sa.String(length=48), nullable=True),
    sa.Column('order_id', sa.String(length=48), nullable=True),
    sa.Column('request_id', sa.String(length=48), nullable=True),
    sa.Column('actor', sa.Enum('CUSTOMER', 'AGENT', 'SYSTEM', 'PAYMENT_PROVIDER', name='auditactor', native_enum=False, length=24), nullable=False),
    sa.Column('action', sa.Enum('PRODUCT_SEARCHED', 'ITEM_ADDED', 'ITEM_REMOVED', 'ITEM_QUANTITY_UPDATED', 'UPSELL_SHOWN', 'UPSELL_ACCEPTED', 'UPSELL_DECLINED', 'CHECKOUT_STARTED', 'CHECKOUT_CANCELLED', 'STOCK_RESERVED', 'STOCK_RELEASED', 'PAYMENT_ATTEMPTED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'PAYMENT_VERIFICATION_FAILED', 'PAYMENT_LINK_CREATED', 'POLICY_BLOCKED', 'CATALOG_SYNCED', 'SESSION_CREATED', 'WEBHOOK_RECEIVED', 'WEBHOOK_REJECTED', name='auditaction', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_session_ref'), ['session_ref'], unique=False)
        batch_op.create_index('ix_audit_session_created', ['session_id', 'created_at'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('order_id', sa.String(length=48), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=256), nullable=True),
    sa.Column('razorpay_payment_link_id', sa.String(length=64), nullable=True),
    sa.Column('payment_link_url', sa.String(length=1024), nullable=True),
    sa.Column('captured_payment_key', sa.String(length=64), nullable=True),
    sa.Column('settled_amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ATTEMPTED', 'AUTHORIZED', 'CAPTURED', 'FAILED', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='ck_payment_attempt_pos'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('captured_payment_key', name='uq_payment_captured_key'),
    sa.UniqueConstraint('order_id', 'attempt_number', name='uq_payment_order_attempt')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_payment_id'), ['razorpay_payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_session_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_session_ref'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_order_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_session_id'))
        batch_op.drop_index(batch_op.f('ix_orders_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_cart_id'))

    op.drop_table('orders')
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))

    op.drop_table('cart_items')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carts_session_id'))

    op.drop_table('carts')
    op.drop_table('webhook_events')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))

    op.drop_table('sessions')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_source'))
        batch_op.drop_index(batch_op.f('ix_products_external_id'))
        batch_op.drop_index('ix_product_sku')
        batch_op.drop_index('ix_product_category')
        batch_op.drop_index('ix_product_active')

    op.drop_table('products')
    # ### end Alembic commands ###
